ServerName localhost
DirectoryIndex index.php

<Directory /var/www/html>
    Options -Indexes
    AllowOverride All
    Require all granted
</Directory>

<Directory /var/www/html/uploads>
    Options -Indexes
    AllowOverride All
    php_admin_flag engine Off
</Directory>

<Directory /var/www/html/config>
    Require all denied
</Directory>

<Directory /var/www/html/install>
    Require all denied
</Directory>

<Directory /var/www/html/backups>
    Require all denied
</Directory>
